// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.alliance.sam;

import com.alliance.sam.ExpedienteRubro;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ExpedienteRubro_Roo_Configurable {
    
    declare @type: ExpedienteRubro: @Configurable;
    
}
